lvm2-conf-initramfs: handle multilib compatibility
The upstream lvm2 recipe is multilib-aware and uses the multilib_script
class and MULTILIB_SCRIPTS variable to apply update-alternative logic
to the lvm2.conf file.

The lvm-conf-initramfs recipe also supplies a lvm.conf file and needs
logic to avoid a build error that occurs with the lvm2.postinst script
when building the rootfs of the initramfs image:

 WARNING: xenclient-initramfs-image-1.0-r0 do_rootfs:
    lvm2.postinst returned 1, marking as unpacked only, configuration
    required on target.

 ERROR: xenclient-initramfs-image-1.0-r0 do_rootfs: Postinstall
    scriptlets of ['lvm2'] have failed. If the intention is to defer
    them to first boot, then please place them into
    pkg_postinst_ontarget_${PN} ().
    Deferring to first boot via 'exit 1' is no longer supported.

Applied here: inherit multilib_script and set MULTILIB_SCRIPTS.

OXT-1694

Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>