openxt-image: Amend long-option format.
opkg no longer accepts non-POSIX long-options format and will interpret
-force-depends as "-f" "orce-depends":
Exception: bb.process.ExecutionError: Execution of '/home/build/openxt/unstable/build-unstable-0/tmp-glibc/work/xenclient_stubdomain-oe-linux/xenclient-stubdomain-initramfs-image/1.0-r0/temp/run.force_package_removal.3382701' failed with exit code 255:
Collected errors:
 * opkg_conf_load: Couldn't stat orce-depends: No such file or directory.

Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>